version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eieimarket
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  eieimarketplace-user-management:
    build: .
    container_name: eieimarketplace-user-management
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eieimarket
      POSTGRES_HOST: postgres
    ports:
      - "7001:7001"

volumes:
  db_data:
